# Generated by Django 3.0.7 on 2020-06-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamathang', models.CharField(max_length=100)),
                ('tenmathang', models.CharField(max_length=100)),
                ('gia', models.CharField(max_length=1000000)),
                ('madonvitinh', models.CharField(max_length=100)),
                ('soluong', models.CharField(max_length=1000)),
                ('maloaimathang', models.CharField(max_length=100)),
            ],
        ),
    ]
