# Generated by Django 3.0.7 on 2020-06-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendaily', models.CharField(max_length=100)),
                ('ngaylapphieu', models.DateTimeField(auto_now_add=True)),
                ('mamathang', models.CharField(max_length=100)),
                ('soluong', models.CharField(max_length=1000)),
                ('tongtien', models.CharField(max_length=1000000)),
                ('maphieuxuathang', models.CharField(max_length=100)),
            ],
        ),
    ]
