# Generated by Django 3.0.7 on 2020-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maphieuthutien', models.CharField(max_length=100)),
                ('mahosodaily', models.CharField(max_length=100)),
                ('ngaythutien', models.DateTimeField(auto_now_add=True)),
                ('sotienthu', models.CharField(max_length=1000000)),
            ],
        ),
    ]
