# Generated by Django 3.0.7 on 2020-06-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendaily', models.CharField(max_length=100)),
                ('mahosodaily', models.CharField(max_length=100)),
                ('dienthoai', models.CharField(max_length=100)),
                ('diachi', models.CharField(max_length=100)),
                ('ngaytiepnhan', models.DateTimeField(auto_now_add=True)),
                ('quan', models.CharField(max_length=100)),
                ('loaidaily', models.CharField(max_length=10)),
            ],
        ),
    ]
